### ISSUE TITLE
push notification configuration fails

### ISSUE THREAD

**Issue by darioesposito01** [get-convex/expo-push-notifications#3]
when i try to create the convex.config.ts and insert the code described in the documentation I get this error; ✘ [ERROR] Could not resolve "@convex-dev/expo-push-notifications/component/convex.config"

    convex/convex.config.js:3:30:
      3 │ import pushNotifications from "@convex-dev/expo-push-notifications/component/convex.config";
        ╵                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  The path "./component/convex.config" is not exported by package
  "@convex-dev/expo-push-notifications":

    node_modules/@convex-dev/expo-push-notifications/package.json:31:13:
      31 │   "exports": {
         ╵              ^

  You can mark the path "@convex-dev/expo-push-notifications/component/convex.config" as external to
  exclude it from the bundle, which will remove this error and leave the unresolved path in the
  bundle.
✖ esbuild failed: Error: Build failed with 1 error:
convex/convex.config.js:3:30: ERROR: Could not resolve "@convex-dev/expo-push-notifications/component/convex.config"

**Comment by ianmacartney** [comment]
Sorry we missed this before. the correct import should be `@convex-dev/expo-push-notifications/convex.config`
there shouldn't be a `/component/` in there
