### ISSUE TITLE
Tamagui ui library as dependencies?

### ISSUE THREAD

**Issue by oscklm** [get-convex/expo-push-notifications#6]
Seems like this pkg is bringing in the whole tamagui ui library as a dependency?

![CleanShot 2024-12-18 at 21 45 31@2x](https://github.com/user-attachments/assets/a20f3feb-3b21-42b9-9206-95714ce27633)

**Comment by erquhart** [comment]
Will be fixed with #5

**Comment by ianmacartney** [comment]
shipped in `@convex-dev/expo-push-notifications@0.1.3`
